services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
       - mysql-data:/var/lib/mysql
  wordpress:
    image: wordpress
    container_name: wordpress-app
    ports:
      - "8080:80"
    environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USE}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWOR}
       WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    depends_on:
       - mysql
volumes:
  mysql-data:
~
